### ISSUE TITLE
Post request content-type isn't setting the value to Json encoding 

### ISSUE THREAD

**Issue by devmustache** [yoxisem544/NetworkRequestKit#4]
```
class PhoneVerificationRequest: NetworkRequest {
    
    public typealias ResponseType = PhoneVerificationResponse
    
    var endpoint: String = "sms/request"
    var method: HTTPMethod = Alamofire.HTTPMethod.post
   
    // I've tried removing this line too:
    var encoding: ParameterEncoding = JSONEncoding.default
    
    public var parameters: [String : Any]?
    
    public func perform() -> Promise<ResponseType> {
        return networkClient.performRequest(self).then(execute: responseHandler)
    }
    
}
```
I'd like to set the content-type to application/json. How I can achieve this? 

Thanks in advance!!

**Comment by yoxisem544** [comment]
I think JSONEncoding.default means content-type application/json. If you're not sure, check Alamofire's documentation, link here: https://github.com/Alamofire/Alamofire/blob/master/Documentation/Usage.md#json-encoding

Hope this link answer your question. :)

**Comment by yoxisem544** [comment]
PromiseKit 6 has some source code changed.
You have to make this
```swift
return networkClient.performRequest(self).then(execute: responseHandler)
```

to this
```swift
return networkClient.performRequest(self).then(responseHandler)
```

execute is no more needed.

**Comment by yoxisem544** [comment]
@marcot91

**Comment by devrandev** [comment]
Cannot convert value of type '(Data) throws -> CityRequest.ResponseType' (aka '(Data) throws -> CityResponseModel') to expected argument type '(_) throws -> _'

on return networkClient.performRequest(self).then(responseHandler)

**Comment by yoxisem544** [comment]
> Cannot convert value of type '(Data) throws -> CityRequest.ResponseType' (aka '(Data) throws -> CityResponseModel') to expected argument type '(_) throws -> _'
> 
> on return networkClient.performRequest(self).then(responseHandler)

Please use Moya. This repo is no longer maintained.
Moya has similar way to handle network requests.
